spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: false

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9822/prueba_exam?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username : postgres
    password: postgres-exam

server:
  port: 6969